# Generated by Django 4.0.1 on 2022-01-17 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria do orçamento', max_length=200, unique=True)),
                ('descricao', models.TextField(help_text='Descrição da categoria do orçamento')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], default='Despesa', help_text='Tipo de orcamento: Receita ou Despesa', max_length=8)),
                ('id_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='conta.categoria')),
            ],
        ),
    ]
