# Generated by Django 4.0.1 on 2022-01-24 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuOrcamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='perfil',
            name='privilegio',
            field=models.IntegerField(choices=[(1, 'Administrador'), (2, 'Usuário')], default=2),
        ),
    ]
