# Generated by Django 4.0.1 on 2022-01-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuOrcamento', '0002_alter_perfil_privilegio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='tipo_orcamento',
            field=models.IntegerField(choices=[(2, 'Despesa'), (1, 'Receita')], default='2'),
        ),
    ]
