# Generated by Django 4.0.1 on 2022-01-27 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuOrcamento', '0003_alter_orcamento_tipo_orcamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='tipo_orcamento',
            field=models.IntegerField(choices=[(1, 'Receita'), (2, 'Despesa')], default='2'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='privilegio',
            field=models.IntegerField(choices=[(2, 'Usuário'), (1, 'Administrador')], default=2),
        ),
    ]
