# Generated by Django 4.0.1 on 2022-01-24 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuOrcamento', '0003_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='orcamentos',
            field=models.ManyToManyField(blank=True, related_name='orcamentos', to='meuOrcamento.Orcamento'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='tipo_orcamento',
            field=models.IntegerField(choices=[(2, 'Despesa'), (1, 'Receita')], default='2'),
        ),
    ]
